apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubevirt-controller-manager
  name: kubevirt-controller-manager
  namespace: cloudplus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubevirt-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubevirt-controller-manager
    spec:
      containers:
      - command:
        - java
        - -jar
        - kubevirt-controller-1.8.0.jar
        image: registry.cn-beijing.aliyuncs.com/dosproj/kubevirt-controller-manager:v1.8.0
        imagePullPolicy: IfNotPresent
        name: kubevirt-controller-manager
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes
          name: admin
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /etc/kubernetes
          type: ""
        name: admin
