---
- name: Create comm service env
  hosts: master:worker
  become: yes
  vars:
    offline:

  tasks:
    - name: Ensure target directory exists
      ansible.builtin.file:
        path: "/etc/uniVirt"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy necessary files to target hosts
      ansible.builtin.synchronize:
        src: "{{ lookup('env', 'PWD') }}/sdsctl/"
        dest: "/etc/uniVirt/sdsctl/"
        recursive: yes
        delete: yes
      become_user: root
    - name: Execute create-comm-service.sh script
      ansible.builtin.command:
        cmd: "bash service.sh"
      args:
        chdir: "{{ lookup('env', 'PWD') }}/scripts/plugins/driverCheck"

    - name: Execute create-comm-service.sh script
      ansible.builtin.command:
        cmd: "bash create-comm-service.sh"
      args:
        chdir: "/etc/uniVirt/sdsctl/grpcservice"
      when: offline is none

    - name: Execute create-comm-service.sh script in offline mode
      ansible.builtin.command:
        cmd: "bash create-comm-service.sh offline"
      args:
        chdir: "/etc/uniVirt/sdsctl/grpcservice"
      when: offline is not none

    - name: Restart kubestack-commctl service
      ansible.builtin.systemd:
        name: kubestack-commctl
        state: restarted
