- hosts: all
  become: yes
  tasks:
    - name: Install Chrony
      package:
        name: chrony
        state: present
      when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

    - name: Configure Chrony
      template:
        src: "{{ 'chrony_chrony.conf.j2' if 'chrony' in group_names else 'chrony_nodes.conf.j2' }}"
        dest: "{{ '/etc/chrony.conf' if 'chrony' in group_names else '/etc/chrony/chrony.conf' }}"
      notify: Restart Chrony
      when: (ansible_os_family == 'RedHat' and 'chrony' in group_names) or (ansible_os_family == 'Debian' and 'chrony' in group_names) or (ansible_os_family == 'RedHat' and ('master' in group_names or 'worker' in group_names) and inventory_hostname != groups['chrony'][0])

    - name: Ensure Chrony service is enabled and started
      service:
        name: "{{ 'chronyd' if ansible_os_family == 'RedHat' else 'chrony' }}"
        state: started
        enabled: yes

  handlers:
    - name: Restart Chrony
      service:
        name: "{{ 'chronyd' if ansible_os_family == 'RedHat' else 'chrony' }}"
        state: restarted
