---
- name: Label Kubernetes Nodes
  hosts: worker
  become: false

  tasks:
    - name: Label centos7 nodes
      command: "kubectl label node {{ item }} doslab/virt.tool.centos="
      when: ansible_os_family == 'RedHat'
      with_items: "{{ ansible_play_batch }}"
      run_once: true

    - name: Label ubuntu22 nodes
      command: "kubectl label node {{ item }} doslab/virt.tool.ubuntu="
      when: ansible_os_family == 'Debian'
      with_items: "{{ ansible_play_batch }}"
      run_once: true
