---
- name: Label Kubernetes Nodes
  hosts: worker
  become: false

  tasks:
    - name: Label centos7 nodes
      command: "kubectl label node {{ item }} doslab/virt.tool.centos="
      when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
      with_items: "{{ ansible_play_batch }}"
      run_once: true

    - name: Label ubuntu22 nodes
      command: "kubectl label node {{ item }} doslab/virt.tool.ubuntu="
      when: ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_version'] == '22.04'
      with_items: "{{ ansible_play_batch }}"
      run_once: true
