---
- name: Install Anaconda3 and Python 3.9.7 on CentOS 7.9
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - bzip2
          - wget
        state: present

    - name: Download Anaconda3 installer
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
        dest: /tmp/Anaconda3-2021.11-Linux-x86_64.sh

    - name: Run Anaconda3 installer
      command: bash /tmp/Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/anaconda3
      args:
        creates: /opt/anaconda3  # Ensure the installer is not run if Anaconda is already installed

    - name: Add Anaconda3 to PATH
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH=/opt/anaconda3/bin:$PATH'
        create: yes

    - name: Reload bashrc to apply changes
      shell: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: /bin/bash

    - name: Install Python 3.9.7 using conda
      command: /opt/anaconda3/bin/conda install -y python=3.9.7

    - name: Create symbolic link for python3.9
      file:
        src: /opt/anaconda3/bin/python
        dest: /usr/local/bin/python3.9
        state: link

    - name: Install pip for Python 3.9.7
      command: /usr/local/bin/python3.9 -m ensurepip
      args:
        creates: /usr/local/bin/pip3.9

    - name: Create symbolic link for pip3.9
      file:
        src: /usr/local/bin/pip3.9
        dest: /usr/local/bin/pip3.9
        state: link

    - name: Verify Python and pip installation
      command: python3.9 --version && pip3.9 --version
