---
- name: Install Anaconda3 and Python 3.10.12 on CentOS 7.9
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - bzip2
          - wget
        state: present

    - name: Download Anaconda3 installer
      get_url:
        url: https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
        dest: /tmp/Anaconda3-2021.11-Linux-x86_64.sh

    - name: Run Anaconda3 installer
      command: bash /tmp/Anaconda3-2021.11-Linux-x86_64.sh -b -p /opt/anaconda3
      args:
        creates: /opt/anaconda3  # Ensure the installer is not run if Anaconda is already installed

    - name: Add Anaconda3 to PATH
      lineinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH=/opt/anaconda3/bin:$PATH'
        create: yes

    - name: Reload bashrc to apply changes
      command: source "{{ ansible_env.HOME }}/.bashrc"
      args:
        executable: bash

    - name: Install Python 3.10.12 using conda
      command: /opt/anaconda3/bin/conda install -y python=3.10.12

    - name: Verify Python installation
      command: /opt/anaconda3/bin/python --version
